/**
 * @file h2_policy_parameters.hpp
 * @brief H2 (31 DOF) analog of policy_parameters.hpp.
 *
 * GENERATED by tools/generate_h2_policy_parameters.py -- edit the generator.
 *
 * Joint order: H2 MJCF tree order (== actuator order). Note vs G1:
 * ankle is ROLL then PITCH, and head pitch/yaw sit at MuJoCo indices 15-16
 * between waist and arms. Upper body = waist 3 + head 2 + arms 14 = 19.
 *
 * Mappings copied from gear_sonic/envs/manager_env/robots/h2.py
 * (H2_ISAACLAB_TO_MUJOCO_MAPPING); gains/action scales computed exactly as
 * that file does (stiffness = armature * (2*pi*10Hz)^2, damping = 2 * zeta *
 * armature * 2*pi*10Hz, zeta = 2; action_scale = 0.25 * effort / stiffness
 * with TRAINING effort limits).
 */

#ifndef H2_POLICY_PARAMETERS_HPP
#define H2_POLICY_PARAMETERS_HPP

#include <array>
#include <vector>

const int H2_NUM_MOTOR = 31;
const int H2_NUM_UPPER_BODY_JOINTS = 19;
const int H2_NUM_LOWER_BODY_JOINTS = 12;

// Motor armature constants (same motor families as G1)
const double H2_ARMATURE_5020 = 0.003609725;
const double H2_ARMATURE_7520_14 = 0.010177520;
const double H2_ARMATURE_7520_22 = 0.025101925;
const double H2_ARMATURE_4010 = 0.00425;

const double H2_NATURAL_FREQ = 10 * 2.0 * 3.1415926535; // 10 Hz
const double H2_DAMPING_RATIO = 2.0;

#define STIFFNESS_OF(a) ((a) * H2_NATURAL_FREQ * H2_NATURAL_FREQ)
#define DAMPING_OF(a) (2.0 * H2_DAMPING_RATIO * (a) * H2_NATURAL_FREQ)
const double STIFFNESS_5020 = STIFFNESS_OF(H2_ARMATURE_5020);
const double STIFFNESS_7520_14 = STIFFNESS_OF(H2_ARMATURE_7520_14);
const double STIFFNESS_7520_22 = STIFFNESS_OF(H2_ARMATURE_7520_22);
const double STIFFNESS_4010 = STIFFNESS_OF(H2_ARMATURE_4010);
const double DAMPING_5020 = DAMPING_OF(H2_ARMATURE_5020);
const double DAMPING_7520_14 = DAMPING_OF(H2_ARMATURE_7520_14);
const double DAMPING_7520_22 = DAMPING_OF(H2_ARMATURE_7520_22);
const double DAMPING_4010 = DAMPING_OF(H2_ARMATURE_4010);
#undef STIFFNESS_OF
#undef DAMPING_OF

// IsaacLab <-> MuJoCo DOF mappings (from robots/h2.py, verified inverses)
const std::array<int, 31> h2_isaaclab_to_mujoco = {
    0, 3, 6, 9, 14, 19, 1, 4,
    7, 10, 15, 20, 2, 5, 8, 11,
    16, 12, 17, 21, 23, 25, 27, 29,
    13, 18, 22, 24, 26, 28, 30
};

const std::array<int, 31> h2_mujoco_to_isaaclab = {
    0, 6, 12, 1, 7, 13, 2, 8,
    14, 3, 9, 15, 17, 24, 4, 10,
    16, 18, 25, 5, 11, 19, 26, 20,
    27, 21, 28, 22, 29, 23, 30
};

// Body-part joint index lists.
// mujoco order = iterate joints in mujoco order; isaaclab order = sorted by
// isaaclab index. "*_in_isaaclab_index" gives the isaaclab dof index of each,
// "*_in_mujoco_index" the mujoco dof index.
const std::vector<int> h2_lower_body_joint_mujoco_order_in_isaaclab_index = {0, 6, 12, 1, 7, 13, 2, 8, 14, 3, 9, 15};

const std::vector<int> h2_lower_body_joint_mujoco_order_in_mujoco_index = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};

const std::vector<int> h2_lower_body_joint_isaaclab_order_in_isaaclab_index = {0, 1, 2, 3, 6, 7, 8, 9, 12, 13, 14, 15};

const std::vector<int> h2_lower_body_joint_isaaclab_order_in_mujoco_index = {0, 3, 6, 9, 1, 4, 7, 10, 2, 5, 8, 11};

const std::vector<int> h2_upper_body_joint_mujoco_order_in_isaaclab_index = {17, 24, 4, 10, 16, 18, 25, 5, 11, 19, 26, 20, 27, 21, 28, 22, 29, 23, 30};

const std::vector<int> h2_upper_body_joint_mujoco_order_in_mujoco_index = {12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30};

const std::vector<int> h2_upper_body_joint_isaaclab_order_in_isaaclab_index = {4, 5, 10, 11, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30};

const std::vector<int> h2_upper_body_joint_isaaclab_order_in_mujoco_index = {14, 19, 15, 20, 16, 12, 17, 21, 23, 25, 27, 29, 13, 18, 22, 24, 26, 28, 30};

const std::vector<int> h2_wrist_joint_mujoco_order_in_isaaclab_index = {19, 26, 20, 29, 23, 30};

const std::vector<int> h2_wrist_joint_mujoco_order_in_mujoco_index = {21, 22, 23, 28, 29, 30};

const std::vector<int> h2_wrist_joint_isaaclab_order_in_isaaclab_index = {19, 20, 23, 26, 29, 30};

const std::vector<int> h2_wrist_joint_isaaclab_order_in_mujoco_index = {21, 23, 29, 22, 28, 30};

// VR tracking body indices (IsaacLab body order, pelvis = 0)
const std::array<int, 3> h2_vr_3point_index = {30, 31, 9}; // l_wrist, r_wrist, torso
const std::array<int, 5> h2_vr_5point_index = {30, 31, 0, 20, 21}; // l_wrist, r_wrist, pelvis, l_ankle, r_ankle

// Action scale: 0.25 * training_effort_limit / stiffness  (mujoco order)
const std::array<double, 31> h2_action_scale = {
    0.25 * 417.0 / (1.0 * STIFFNESS_7520_22), // left_hip_pitch_joint
    0.25 * 417.0 / (1.0 * STIFFNESS_7520_22), // left_hip_roll_joint
    0.25 * 264.0 / (1.0 * STIFFNESS_7520_14), // left_hip_yaw_joint
    0.25 * 417.0 / (1.0 * STIFFNESS_7520_22), // left_knee_joint
    0.25 * 150.0 / (2.0 * STIFFNESS_5020), // left_ankle_roll_joint
    0.25 * 150.0 / (2.0 * STIFFNESS_5020), // left_ankle_pitch_joint
    0.25 * 417.0 / (1.0 * STIFFNESS_7520_22), // right_hip_pitch_joint
    0.25 * 417.0 / (1.0 * STIFFNESS_7520_22), // right_hip_roll_joint
    0.25 * 264.0 / (1.0 * STIFFNESS_7520_14), // right_hip_yaw_joint
    0.25 * 417.0 / (1.0 * STIFFNESS_7520_22), // right_knee_joint
    0.25 * 150.0 / (2.0 * STIFFNESS_5020), // right_ankle_roll_joint
    0.25 * 150.0 / (2.0 * STIFFNESS_5020), // right_ankle_pitch_joint
    0.25 * 264.0 / (1.0 * STIFFNESS_7520_14), // waist_yaw_joint
    0.25 * 150.0 / (2.0 * STIFFNESS_5020), // waist_roll_joint
    0.25 * 150.0 / (2.0 * STIFFNESS_5020), // waist_pitch_joint
    0.25 * 150.0 / (2.0 * STIFFNESS_5020), // head_pitch_joint
    0.25 * 150.0 / (2.0 * STIFFNESS_5020), // head_yaw_joint
    0.25 * 75.0 / (1.0 * STIFFNESS_5020), // left_shoulder_pitch_joint
    0.25 * 75.0 / (1.0 * STIFFNESS_5020), // left_shoulder_roll_joint
    0.25 * 75.0 / (1.0 * STIFFNESS_5020), // left_shoulder_yaw_joint
    0.25 * 75.0 / (1.0 * STIFFNESS_5020), // left_elbow_joint
    0.25 * 75.0 / (1.0 * STIFFNESS_5020), // left_wrist_roll_joint
    0.25 * 15.0 / (1.0 * STIFFNESS_4010), // left_wrist_pitch_joint
    0.25 * 15.0 / (1.0 * STIFFNESS_4010), // left_wrist_yaw_joint
    0.25 * 75.0 / (1.0 * STIFFNESS_5020), // right_shoulder_pitch_joint
    0.25 * 75.0 / (1.0 * STIFFNESS_5020), // right_shoulder_roll_joint
    0.25 * 75.0 / (1.0 * STIFFNESS_5020), // right_shoulder_yaw_joint
    0.25 * 75.0 / (1.0 * STIFFNESS_5020), // right_elbow_joint
    0.25 * 75.0 / (1.0 * STIFFNESS_5020), // right_wrist_roll_joint
    0.25 * 15.0 / (1.0 * STIFFNESS_4010), // right_wrist_pitch_joint
    0.25 * 15.0 / (1.0 * STIFFNESS_4010), // right_wrist_yaw_joint
};

// PD gains (mujoco order) -- must match the sim yaml and training config
const std::array<float, 31> h2_kps = {
    STIFFNESS_7520_22, // left_hip_pitch_joint
    STIFFNESS_7520_22, // left_hip_roll_joint
    STIFFNESS_7520_14, // left_hip_yaw_joint
    STIFFNESS_7520_22, // left_knee_joint
    2.0 * STIFFNESS_5020, // left_ankle_roll_joint
    2.0 * STIFFNESS_5020, // left_ankle_pitch_joint
    STIFFNESS_7520_22, // right_hip_pitch_joint
    STIFFNESS_7520_22, // right_hip_roll_joint
    STIFFNESS_7520_14, // right_hip_yaw_joint
    STIFFNESS_7520_22, // right_knee_joint
    2.0 * STIFFNESS_5020, // right_ankle_roll_joint
    2.0 * STIFFNESS_5020, // right_ankle_pitch_joint
    STIFFNESS_7520_14, // waist_yaw_joint
    2.0 * STIFFNESS_5020, // waist_roll_joint
    2.0 * STIFFNESS_5020, // waist_pitch_joint
    2.0 * STIFFNESS_5020, // head_pitch_joint
    2.0 * STIFFNESS_5020, // head_yaw_joint
    STIFFNESS_5020, // left_shoulder_pitch_joint
    STIFFNESS_5020, // left_shoulder_roll_joint
    STIFFNESS_5020, // left_shoulder_yaw_joint
    STIFFNESS_5020, // left_elbow_joint
    STIFFNESS_5020, // left_wrist_roll_joint
    STIFFNESS_4010, // left_wrist_pitch_joint
    STIFFNESS_4010, // left_wrist_yaw_joint
    STIFFNESS_5020, // right_shoulder_pitch_joint
    STIFFNESS_5020, // right_shoulder_roll_joint
    STIFFNESS_5020, // right_shoulder_yaw_joint
    STIFFNESS_5020, // right_elbow_joint
    STIFFNESS_5020, // right_wrist_roll_joint
    STIFFNESS_4010, // right_wrist_pitch_joint
    STIFFNESS_4010, // right_wrist_yaw_joint
};

const std::array<float, 31> h2_kds = {
    DAMPING_7520_22, // left_hip_pitch_joint
    DAMPING_7520_22, // left_hip_roll_joint
    DAMPING_7520_14, // left_hip_yaw_joint
    DAMPING_7520_22, // left_knee_joint
    2.0 * DAMPING_5020, // left_ankle_roll_joint
    2.0 * DAMPING_5020, // left_ankle_pitch_joint
    DAMPING_7520_22, // right_hip_pitch_joint
    DAMPING_7520_22, // right_hip_roll_joint
    DAMPING_7520_14, // right_hip_yaw_joint
    DAMPING_7520_22, // right_knee_joint
    2.0 * DAMPING_5020, // right_ankle_roll_joint
    2.0 * DAMPING_5020, // right_ankle_pitch_joint
    DAMPING_7520_14, // waist_yaw_joint
    2.0 * DAMPING_5020, // waist_roll_joint
    2.0 * DAMPING_5020, // waist_pitch_joint
    2.0 * DAMPING_5020, // head_pitch_joint
    2.0 * DAMPING_5020, // head_yaw_joint
    DAMPING_5020, // left_shoulder_pitch_joint
    DAMPING_5020, // left_shoulder_roll_joint
    DAMPING_5020, // left_shoulder_yaw_joint
    DAMPING_5020, // left_elbow_joint
    DAMPING_5020, // left_wrist_roll_joint
    DAMPING_4010, // left_wrist_pitch_joint
    DAMPING_4010, // left_wrist_yaw_joint
    DAMPING_5020, // right_shoulder_pitch_joint
    DAMPING_5020, // right_shoulder_roll_joint
    DAMPING_5020, // right_shoulder_yaw_joint
    DAMPING_5020, // right_elbow_joint
    DAMPING_5020, // right_wrist_roll_joint
    DAMPING_4010, // right_wrist_pitch_joint
    DAMPING_4010, // right_wrist_yaw_joint
};

// Default standing pose (mujoco order), from H2_CFG.init_state
const std::array<double, 31> h2_default_angles = {
    -0.312, // left_hip_pitch_joint
    0.0, // left_hip_roll_joint
    0.0, // left_hip_yaw_joint
    0.669, // left_knee_joint
    0.0, // left_ankle_roll_joint
    -0.363, // left_ankle_pitch_joint
    -0.312, // right_hip_pitch_joint
    0.0, // right_hip_roll_joint
    0.0, // right_hip_yaw_joint
    0.669, // right_knee_joint
    0.0, // right_ankle_roll_joint
    -0.363, // right_ankle_pitch_joint
    0.0, // waist_yaw_joint
    0.0, // waist_roll_joint
    0.0, // waist_pitch_joint
    0.0, // head_pitch_joint
    0.0, // head_yaw_joint
    0.2, // left_shoulder_pitch_joint
    0.2, // left_shoulder_roll_joint
    0.0, // left_shoulder_yaw_joint
    0.6, // left_elbow_joint
    0.0, // left_wrist_roll_joint
    0.0, // left_wrist_pitch_joint
    0.0, // left_wrist_yaw_joint
    0.2, // right_shoulder_pitch_joint
    -0.2, // right_shoulder_roll_joint
    0.0, // right_shoulder_yaw_joint
    0.6, // right_elbow_joint
    0.0, // right_wrist_roll_joint
    0.0, // right_wrist_pitch_joint
    0.0, // right_wrist_yaw_joint
};

#endif // H2_POLICY_PARAMETERS_HPP
